<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Il2CppAirship.LuauCore">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\Il2CppAssemblies\Il2CppAirship.LuauCore.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppLuauAPI">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\Il2CppAssemblies\Il2CppLuauAPI.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystem.Windows.Forms">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\Il2CppAssemblies\Il2CppSystem.Windows.Forms.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\Unity\Projects\airship-template\build\client_windows\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /-I /y &quot;D:\Visual Studio Projects\HindenburgDll\HindenburgDll\bin\Debug\net6.0\HindenburgDll.dll&quot; D:\Unity\Projects\airship-template\build\client_windows\Mods\HindenburgDll.dll" />
  </Target>

</Project>
